import os
import sys
import psycopg2
from dotenv import load_dotenv

# This is a one-time setup script used to create the required table in Supabase
# You only need to run this script when:
# 1. Setting up the project for the first time
# 2. If you need to recreate the table or modify its structure
# Keep this script for future reference or table structure modifications

def main():
    # Load environment variables
    load_dotenv()
    
    # Get Supabase PostgreSQL connection details
    db_host = os.environ.get("host")
    db_port = os.environ.get("port")
    db_name = os.environ.get("dbname")
    db_user = os.environ.get("user")
    db_password = os.environ.get("password")
    
    # SQL to create the table
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS public.product (
      id bigint generated by default as identity not null,
      sku text null,
      name text null,
      brand_id uuid null default gen_random_uuid(),
      url text null,
      slug text null,
      type text null,
      category text null,
      colors text[] null,
      sizes text[] null,
      short_description text[] null,
      long_description text null,
      collection text null,
      rating double precision null,
      is_new boolean null,
      is_sale boolean null,
      material text[] null,
      technique text[] null,
      img_url text[] null,
      has_detaild_info boolean null,
      created_at timestamp with time zone not null default now(),
      constraint product_pkey primary key (id),
      constraint product_id_key unique (id),
      constraint product_sku_key unique (sku)
    ) TABLESPACE pg_default;
    """
    
    print("Setting up Supabase product table...")
    
    # Test if we have all the connection details
    if not all([db_host, db_port, db_name, db_user, db_password]):
        print("Error: Missing database connection details in .env file")
        print("\nPlease ensure your .env file has these PostgreSQL connection details:")
        print("host=<your-supabase-db-host>")
        print("port=<your-supabase-db-port>")
        print("dbname=<your-supabase-db-name>")
        print("user=<your-supabase-db-user>")
        print("password=<your-supabase-db-password>")
        print("\nAlternatively, create the table manually in Supabase dashboard with this SQL:")
        print(create_table_sql)
        return 1
    
    try:
        # Connect to the PostgreSQL database
        print(f"Connecting to PostgreSQL database at {db_host}:{db_port}...")
        conn = psycopg2.connect(
            host=db_host,
            port=db_port,
            dbname=db_name,
            user=db_user,
            password=db_password
        )
        
        # Create a cursor
        cur = conn.cursor()
        
        # Check if the table exists
        check_table_sql = """
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public'
            AND table_name = 'product'
        );
        """
        
        cur.execute(check_table_sql)
        table_exists = cur.fetchone()[0]
        
        if table_exists:
            print("Table 'product' already exists!")
        else:
            print("Creating table 'product'...")
            print(f"Executing SQL:\n{create_table_sql}")
            
            # Execute the SQL to create the table
            cur.execute(create_table_sql)
            
            # Commit the transaction
            conn.commit()
            
            print("Table 'product' created successfully!")
        
        # Close the cursor and connection
        cur.close()
        conn.close()
        
        print("\nSetup completed successfully!")
        return 0
        
    except Exception as e:
        print(f"Error: {str(e)}")
        print("\nPlease create the table manually in Supabase dashboard with this SQL:")
        print(create_table_sql)
        return 1

if __name__ == "__main__":
    sys.exit(main()) 